### ISSUE TITLE
keep getting transfered failure error

### ISSUE THREAD

**Issue by nerdess** [p3pp8/remotesynch#1]
i'd love to use your extension but....either i am too noob (i just recently switched from sublime to vsc) or your extension is still a bit buggy...

so i init the extension, add my ftp credentials to remoteSync.json, change and save some random file and hope for the synchOnSave to do its magic. unfortunately, i always get "xyz.css transfered failure". i cannot figure our where the configuration is wrong though because the ftp credentials are 100% correct (they work with e.g. the ftp-sync extension).

here my remoteSynch.json (without the correct ftp credentials of course):

{
    "username": "xyz",
    "password": "password",
    "remoteHost": "bla.blubb.com",
    "remotePath": "/",
    "localPath": "/",
    "synchOnSave": true,
    "secure": false
}

any help is appreciated :)

**Comment by p3pp8** [comment]
Hello, of course it possibly is a little buggy but let's try to resolve your issue. Please try removing  localPath(has it's the project root) from your configuration JSON: 
```
{
    "username": "xyz",
    "password": "password",
    "remoteHost": "bla.blubb.com",
    "remotePath": "/",
    "synchOnSave": true,
    "secure": false
}
```

If it's still not working i'll put some debug info to get more info.

Let me know!

PS: Could you check VSC output or debug console tabs to see if any error is displayed when you execute the synch?

**Comment by p3pp8** [comment]
Ok i've dug out the problem, in case of `non secure` transfer i've to use `CURL` to upload files, `SCP` requires a secure transfer. 
I gonna update the extension ASAP but you have to install CURL on your system in case it's not already available, Mac OSX has it already installed by default.

**Comment by p3pp8** [comment]
Extension has been updated.
